Convert all System.Diagnostics.Process.Start() to use Tools.OpenUrlInBrowser() function which is error supressed to prevent
System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo
startInfo)
   at System.Diagnostics.Process.Start()